#!/bin/bash

# Font settings
XFCE4_FONT_DEFAULT="Sans 10"
XFCE4_FONT_MONO="Monospace 10"

# Panel settings
XFCE4_PANEL_CLOCK_FORMAT="%m/%d, %H:%M:%S"

# xfce4 themes
XFCE4_THEME=Qogir-dark
XFCE4_THEME_ARCHIVE=theme-Qogir-dark.tar.xz

XFCE4_ICON=Qogir-dark
XFCE4_ICON_ARCHIVE=icons-Qogir.tar.xz

XFCE4_CURSOR=Qogir

# Lightdm

LIGHTDM_BACKGROUND=pexels-frans-van-heerden-624015.jpg
LIGHTDM_THEME=$XFCE4_THEME
LIGHTDM_ICON_THEME=$XFCE4_ICON
LIGHTDM_CURSOR_THEME=$XFCE4_CURSOR
LIGHTDM_CURSOR_SIZE=16
LIGHTDM_FONT=$XFCE4_FONT_DEFAULT
